### ISSUE TITLE
Adding VAVAILABILITY gives no privilege error

### ISSUE THREAD

**Issue by signalarun** [sabre-io/sabre.io#110]
<s:sabredav-version>3.1.3</s:sabredav-version>
    <s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
    <s:message>User did not have the required privileges ({DAV:}write-content) for path "calendars/arun/inbox"</s:message>

**Comment by ByteHamster** [comment]
This is the repo of the sabre.io website, not of sabre/dav. Given that the issue is more than 3 years old and not relevant to this repo, I am closing it now.
