### ISSUE TITLE
The example Apache configuration fails on </VirtualHost *:*> closing tag

### ISSUE THREAD

**Issue by baldpenguin** [sabre-io/sabre.io#124]
The example Apache configuration fails on </VirtualHost *:*> closing tag
Following the instructions from http://sabre.io/dav/webservers/

Checking Apache configuration:
# apachectl configtest
apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 26 of /etc/apache2/sites-enabled/sabredav.conf: </VirtualHost> directive missing closing '>'
Action 'configtest' failed.

Solution:
change: 
`</VirtualHost *:*>
`into:  
`</VirtualHost>
`
For more information, see the Apache2 VirtualHost example page:
https://httpd.apache.org/docs/2.4/vhosts/examples.html

**Comment by staabm** [comment]
Thx for the hint. Are you willing to provide a Pull Request with a fix?

Source is on https://github.com/sabre-io/sabre.io/blob/master/source/dav/webservers.md

**Comment by baldpenguin** [comment]
No, I am unable to do this at the moment.
I just noticed that these files are affected as well:
/vendor/sabre/dav/examples/webserver/apache2_vhost.conf is 
/vendor/sabre/dav/examples/webserver/apache2_vhost_cgi.conf
(I'm using Apache 2.4.38-3+deb10u1)

**Comment by staabm** [comment]
Thx for the hints

**Comment by staabm** [comment]
@evert could you re-depoly the website when time allows?
