### ISSUE TITLE
Site broken on https

### ISSUE THREAD

**Issue by ByteHamster** [sabre-io/sabre.io#126]
Over https (like it is listed on Google), the whole sabre-io is broken:
<img width="250" src="https://user-images.githubusercontent.com/5811634/68797399-d2178e00-0654-11ea-91f1-8891d23eac04.png" />

That seems to happen because the `{{ site.url }}` variable has a hard-coded `http://` in it, triggering a `MixedContent` error:

> Mixed Content: The page at 'https://sabre.io/baikal/' was loaded over HTTPS, but requested an insecure stylesheet 'http://sabre.io/css/sabre.css'. This request has been blocked; the content must be served over HTTPS.

I do not know where to configure this variable. Also, I do not know how to deploy the page afterwards, so I can't help with a PR here.

**Comment by staabm** [comment]
I guess we need to fix the url here:
https://github.com/sabre-io/sabre.io/blob/3336ad0fdfa1c88471066243d65a143a3a41d81c/Makefile#L6

**Comment by staabm** [comment]
I fixed a few http occurences.

@evert how to deploy this changes?
Could we get a automated deployment on changes in the master branch (e.g. via github actions or travis CI)?

**Comment by evert** [comment]
I haven't done this in a while, but normally the way this is deployed .. is a bit clunky.

There's 2 repositories:

* This one
* https://github.com/fruux/fruux.github.io

The second one just contains the 'built' files. We should probably just move that second one to the `sabre-io` org.

But effectively the steps are:

1. Run the build script from the source repo
2. Put the build files onto the "fruux.github.io" repo
3. Push that branch

There's some scripts that help automate this. Unfortunately this is all pretty ancient now and uses tooling that's no longer maintained, like Sculpin.

**Comment by ByteHamster** [comment]
@staabm Do you have access to the `fruux/fruux.github.io` repo? I would love to push the fix but I don't have the necessary permissions.

**Comment by staabm** [comment]
> Do you have access to the `fruux/fruux.github.io` repo? I would love to push the fix but I don't have the necessary permissions.

I dont think so.

**Comment by staabm** [comment]
Seems to be deployed now:

https://twitter.com/fruux/status/1217390639215673345?s=20

**Comment by ByteHamster** [comment]
Who deployed the website update? It would be good to have this automated. Before the next Baikal release, I want the new upgrade instructions (#129) to be available on the website to prevent data loss.

**Comment by evert** [comment]
My guess is @DominikTo  ? It would probably be good for others to have access to this

**Comment by DominikTo** [comment]
Yes, that was me, after a quick ping from @staabm. I have it on my list, but sadly didn't quite get around to it yet. But if you need an update deployed, you can always ping me.

**Comment by ByteHamster** [comment]
> But if you need an update deployed, you can always ping me.

Ping ;)

Baikal's upgrade instructions have been changed. Just following the old ones can lead to data loss.

**Comment by DominikTo** [comment]
Done. :)
