### ISSUE TITLE
https://sabre.io/ns%22%3E Not found

### ISSUE THREAD

**Issue by DrAxelbauer** [sabre-io/sabre.io#131]
Hi there!
Webpage informed that i should tell this broken link:

https://sabre.io/ns/

**Comment by DeepDiver1975** [comment]
> https://sabre.io/ns/

if you are referring to this as the xml namespace this is a 'won't fix'.
xml namespaces follow the url schema but there is no necessity that anything is served by this url.
xml namespaces are unique identifiers - nothing more ...
