### ISSUE TITLE
Dockerized installation on https://sabre.io points to outdated image

### ISSUE THREAD

**Issue by smainz** [sabre-io/sabre.io#132]
The documentation on https://sabre.io/baikal/docker-install/ refers to the very outdated docker image, `pr3d4t0r/calendar` which is not maintained (uses baikal version 0.4.6)

There is an activly developed docker image `ckulka/baikal`:
- https://github.com/ckulka/baikal-docker 
- https://hub.docker.com/r/ckulka/baikal

Maybe it's worth changing the the link to this one.

**Comment by staabm** [comment]
If the docker maintainer is trustworthy... I am ok with it

**Comment by ckulka** [comment]
Hi @staabm , not going to say that I am of course trustworthy, but if you and/or others from sabre-io would like to meet up in a video chat to talk about it, just let me know.

**Comment by ByteHamster** [comment]
The container is maintained since 2016, has a fair amount of stars (39) and has good documentation. I would still state that the container is unofficial but it is definitely way better than the outdated one we currently promote (which has known vulnerabilities like https://github.com/sabre-io/Baikal/issues/673).

I'll propose a PR soon.

**Comment by smainz** [comment]
As I started this issue, I volunteer to prepare a PR to the documentation.
Are you interested?

**Comment by ByteHamster** [comment]
Oh, that would be pretty nice! :+1: I think we should keep the text rather short. We don't have to copy (and update) the setup instructions because they already are available in the repo. So the PR would probably mostly delete things.

**Comment by ByteHamster** [comment]
Fixed in #134. @staabm Could you please push the update to the website when you have some time (I wish this repo had CI)?

**Comment by staabm** [comment]
I dont have the permission/tools to push website updates

**Comment by ByteHamster** [comment]
Oh, right. Sorry.

@DominikTo Ping ;) Could you please deploy the website?
