### ISSUE TITLE
Deploy to Website

### ISSUE THREAD

**Issue by smainz** [sabre-io/sabre.io#138]
In April my PR #134 regarding outdated docker install instructions has been accepted, but on the Website there still is the old version.

Can anyone please depoy this?

**Comment by staabm** [comment]
@DominikTo I guess you are the only one with the required credentials

**Comment by DominikTo** [comment]
Ah, damn. That reminds me that I wanted to automate this. Will trigger a deploy shortly and report back here.

**Comment by DominikTo** [comment]
Done.

**Comment by smainz** [comment]
Thanks

**Comment by DeepDiver1975** [comment]
> Ah, damn. That reminds me that I wanted to automate this.

Any news on automation? Has this been taken care of?
Also to reduce the bus factor here: who else can do the deployment? THX

**Comment by DominikTo** [comment]
Will take care of it.

**Comment by DeepDiver1975** [comment]
> Will take care of it.

THX a lot - as an more open approach we could move the site over to github pages.

I can look into the technical side if this is of interest.

**Comment by phil-davis** [comment]
@DominikTo does the web site auto-deploy these days when this repo changes?
(I will make some small change anyway, and see if any "magic" happens)

**Comment by DominikTo** [comment]
It sadly does not and I didn't get around yet to get the deploy script up and running locally again.

**Comment by DeepDiver1975** [comment]
due to #157 we have an autodeployed site again on https://sabre-io.github.io/sabre.io/

@DominikTo let's chat on how to redirect https://sabre.io to github pages - thx

**Comment by staabm** [comment]
having it as a github pages site is perfect, thank you!

**Comment by DeepDiver1975** [comment]
if we are fine to have it pure under https://sabre-io.github.io/sabre.io/ - some hard coded links within the source code need adaptation.

**Comment by ByteHamster** [comment]
Doesn't that break external links, search engines, etc? Can't we set the dns of sabre.io to GitHub, so it stays on the same domain?

**Comment by DeepDiver1975** [comment]
We for sure can do that....
We = @DominikTo

**Comment by DominikTo** [comment]
Oh this is great! The old deploy script would have needed quite significant updates to work again.
Let me check on setting up the domain for GH pages.

**Comment by DominikTo** [comment]
@DeepDiver1975:

DNS is now hooked up for this repo/org.
But GH UI added the CNAME file to the gh-pages branch when adding the domain, guess that should move into the master branch, so it gets added for deploys. And seems like links need to be updated. On the currently live page all links go to the github.io URL instead of sabre.io

**Comment by DeepDiver1975** [comment]
> will have a look as well ....

@DominikTo have you setup the DNS records a defined in https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages ?

**Comment by DominikTo** [comment]
Yes, but interestingly enough the UI did not give me a TXT record for verification.
Saw "DNS verified" straight away and it committed the CNAME file into the gh-pages branch.

If non-async is easier: Available via Twitter DM or on Matrix.

**Comment by DominikTo** [comment]
Just realized that adding domain to GH pages and verifying are two separate processes.
Now also verified for sabre-io org.

**Comment by phil-davis** [comment]
I tried fixing something in the docs - PR #164 
It was published on merge correctly, good.
So we are able to update documentation and publish it nowadays.

**Comment by phil-davis** [comment]
This seems to be working. So I will close the issue. Feel free to re-open if there is more needed to be done.

(of course the actual docs content needs to be got up-to-date, but that is a separate task!)
