### ISSUE TITLE
Google Analytics still in use?

### ISSUE THREAD

**Issue by Rotzbua** [sabre-io/sabre.io#147]
## Problem

The current Google Analytics script code is outdated:
https://github.com/sabre-io/sabre.io/blob/9e96b7fb2ad853daaed7cc5412e580fb6832b62c/source/_includes/ga.html

## Solution

1. Remove GA
2. Update script code

**Comment by DeepDiver1975** [comment]
@DominikTo can you answer? Generally speaking I'd say we drop it .... unless there is any need ....

**Comment by DominikTo** [comment]
Agree, let’s remove for now. Can re-add something else later. Maybe Plausible.
